from typing import Any, Protocol

from handover_ai.domain.documents import StoredDocument


class DocumentRepository(Protocol):
    def save_document(self, document: StoredDocument) -> None: ...

    def get_document(self, document_id: str) -> StoredDocument | None: ...

    def get_by_hash(self, file_sha256: str) -> StoredDocument | None: ...

    def list_documents(self, limit: int, offset: int) -> list[StoredDocument]: ...


class TaskRepository(Protocol):
    def get_task(self, task_id: str) -> dict[str, Any] | None: ...

    def list_tasks(self, limit: int = 100) -> list[dict[str, Any]]: ...


class EvaluationRepository(Protocol):
    def save_evaluation(self, evaluation: dict[str, Any]) -> None: ...


class UnitOfWork(Protocol):
    def __enter__(self): ...

    def __exit__(self, exception_type, exception, traceback): ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
