from typing import Any, Protocol


class DocumentRepository(Protocol):
    def save_document(self, document: dict[str, Any]) -> None: ...

    def get_document(self, document_id: str) -> dict[str, Any] | None: ...


class TaskRepository(Protocol):
    def get_task(self, task_id: str) -> dict[str, Any] | None: ...

    def list_tasks(self, limit: int = 100) -> list[dict[str, Any]]: ...


class EvaluationRepository(Protocol):
    def save_evaluation(self, evaluation: dict[str, Any]) -> None: ...


class UnitOfWork(Protocol):
    def __enter__(self): ...

    def __exit__(self, exception_type, exception, traceback): ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
